### ISSUE TITLE
Update Looping

### ISSUE THREAD

**Issue by fr0stedfl4ke** [1N3/Sn1per#179]
Whenever you run and/or attempt to update the tool it pulls down an older version of the product, 5.10. The tool appears to be on 6.0 as of today. Even after the update, it still indicates that it's out of date.

**Comment by 1N3** [comment]
Thanks for the heads up and sorry about that! This is now fixed in the current v6.0 branch!

**Comment by fr0stedfl4ke** [comment]
Update looping still exists, but for the existing version. The tool found an update, downloaded and installed applicable tools. Ran update once more and it states that there's a new update. 

![image](https://user-images.githubusercontent.com/42190475/49184630-c5e7d300-f314-11e8-9386-fa48458fbc87.png)

**Comment by 1N3** [comment]
Can you try running the following command to confirm if the output says 6.0? I've noticed that if I don't have an internet connection, the curl command doesn't return anything and causing the logic in the update check to fail, so also confirm you have a valid internet connection as well.

curl --connect-timeout 3 -s https://api.github.com/repos/1N3/Sn1per/tags | grep -Po '"name":.*?[^\\]",'| head -1 | cut -c11-13

**Comment by fr0stedfl4ke** [comment]
The output states 6.0. After I run sniper -u, the tool confirms Sn1per is up-to-date. This must have been a internet connection issue on my end. Thanks for pointing that out.

**Comment by 1N3** [comment]
Cool. Glad it’s working now. I’ll see if I can add a change to check for an active connection prior to checking which should help.
